# codegen.toml

[[models]]
path = "."
files = [ "wasmcloud-actor.smithy" ]

[tinygo]
output_dir = ""
formatter = [ "goimports", "-w" ]
files = [
    { path = "tinygo/actor.go", package="actor", namespace = "org.wasmcloud.actor" },
]


#[[rust.files]]
#path = "../src/wasmbus_core.rs"
#namespace = "org.wasmcloud.core"
#crate = "wasmbus_core"

#[[rust.files]]
#path = "../../../codegen/src/wasmbus_model.rs"
#namespace = "org.wasmcloud.model"
#crate = "wasmbus_rpc_model"

#[python]
#output_dir = "python"
#
#[[python.files]]
#path = "wasmbus_core.py"
#namespace = "org.wasmcloud.core"
#
#[[python.files]]
#path = "wasmbus_model.py"
#namespace = "org.wasmcloud.model"

